### ISSUE TITLE
Weird behavior when you register & try to unregister a method subscriber & field subscriber

### ISSUE THREAD

**Issue by Trol1337** [Shyrogan/Tibi#1]
Having one public event manager instance 
`private final EventManager manager = new EventManager()`
Registering a class containing
```
@Subscribe
private Listener<EventTest> event = e -> {};
```
and 
```
@Subscribe
private void onEvent(EventTest event) {

}
```
and running `eventManager.unregister(object)` will not unregister the method subscriber, but will unregister the field subscriber.

**Comment by Shyrogan** [comment]
Shyrogan@36889a7d03d24139e596deca3e519d04a163f544
